### ISSUE TITLE
Arquillian tests hang on cleanup in Wildfly 10 

### ISSUE THREAD

**Issue by scottkurz** [radcortez/wildfly-spring-batch#3]
Tried these instructions..pretty neat, thanks for writing this up.

Running wildfly-10.0.0.Final with Java 8. 

I can see the test ran successfully in the server, but the text execution hangs in the **mvn** JVM after

```
Running com.cortez.wildfly.batch.batchlet.MyBatchletSpringBatchTest
408696e7-1256-408b-9762-e6b4e16a2e01.war:
...
Apr 12, 2016 6:25:45 PM org.jboss.remoting3.EndpointImpl <clinit>
INFO: JBoss Remoting version (unknown)
```

The reason seems to be related to these messages in the server output

```
18:32:09,796 INFO  [org.jboss.weld.deployer] (MSC service thread 1-2) WFLYWELD0010: Stopping weld service for deployment 260d9c32-1507-4414-ba2a-d8a65816f2ee.war
18:32:09,801 ERROR [stderr] (ServerService Thread Pool -- 72) Exception in thread "ServerService Thread Pool -- 72" javax.batch.operations.NoSuchJobException: Job name: batchlet not found.
18:32:09,802 ERROR [stderr] (ServerService Thread Pool -- 72)   at org.springframework.batch.core.jsr.launch.JsrJobOperator.getRunningExecutions(JsrJobOperator.java:372)
18:32:09,802 ERROR [stderr] (ServerService Thread Pool -- 72)   at org.wildfly.extension.batch.jberet.impl.BatchEnvironmentService$BatchJobServerActivity.stopRunningJobs(BatchEnvironmentService.java:320)
18:32:09,802 ERROR [stderr] (ServerService Thread Pool -- 72)   at org.wildfly.extension.batch.jberet.impl.BatchEnvironmentService$BatchJobServerActivity.access$800(BatchEnvironmentService.java:286)
18:32:09,803 ERROR [stderr] (ServerService Thread Pool -- 72)   at org.wildfly.extension.batch.jberet.impl.BatchEnvironmentService.lambda$stop$4(BatchEnvironmentService.java:142)
18:32:09,803 ERROR [stderr] (ServerService Thread Pool -- 72)   at org.wildfly.extension.batch.jberet.impl.BatchEnvironmentService$$Lambda$117.000000001A443AC0.run(Unknown Source)
18:32:09,803 ERROR [stderr] (ServerService Thread Pool -- 72)   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
18:32:09,804 ERROR [stderr] (ServerService Thread Pool -- 72)   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
18:32:09,804 ERROR [stderr] (ServerService Thread Pool -- 72)   at java.lang.Thread.run(Thread.java:785)
18:32:09,804 ERROR [stderr] (ServerService Thread Pool -- 72)   at org.jboss.threads.JBossThread.run(JBossThread.java:320)

18:37:09,726 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) WFLYCTL0348: Timeout after [300] seconds waiting for service container stability. Operation will roll back. Step that first updated the service container was 'undeploy' at address '[("deployment" => "260d9c32-1507-4414-ba2a-d8a65816f2ee.war")]'
18:37:14,728 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) WFLYCTL0190: Step handler org.jboss.as.server.deployment.DeploymentHandlerUtil$5@98125c62 for operation {"operation" => "undeploy","address" => [("deployment" => "260d9c32-1507-4414-ba2a-d8a65816f2ee.war")],"operation-headers" => {"caller-type" => "user","access-mechanism" => "NATIVE"}} at address [("deployment" => "260d9c32-1507-4414-ba2a-d8a65816f2ee.war")] failed handling operation rollback -- java.lang.IllegalStateException: WFLYCTL0345: Timeout after 5 seconds waiting for existing service service jboss.deployment.unit."260d9c32-1507-4414-ba2a-d8a65816f2ee.war".contents to be removed so a new instance can be installed.: java.lang.IllegalStateException: WFLYCTL0345: Timeout after 5 seconds waiting for existing service service jboss.deployment.unit."260d9c32-1507-4414-ba2a-d8a65816f2ee.war".contents to be removed so a new instance can be installed.
        at org.jboss.as.controller.OperationContextImpl$ContextServiceBuilder.install(OperationContextImpl.java:2122)
        at org.jboss.as.server.deployment.ContentServitor.addService(ContentServitor.java:48)
        at org.jboss.as.server.deployment.DeploymentHandlerUtil.doDeploy(DeploymentHandlerUtil.java:161)
        at org.jboss.as.server.deployment.DeploymentHandlerUtil$5$1.handleResult(DeploymentHandlerUtil.java:331)
        at org.jboss.as.controller.AbstractOperationContext$Step.invokeResultHandler(AbstractOperationContext.java:1384)
        at org.jboss.as.controller.AbstractOperationContext$Step.handleResult(AbstractOperationContext.java:1366)
        at org.jboss.as.controller.AbstractOperationContext$Step.finalizeInternal(AbstractOperationContext.java:1328)
        at org.jboss.as.controller.AbstractOperationContext$Step.finalizeStep(AbstractOperationContext.java:1311)
        at org.jboss.as.controller.AbstractOperationContext$Step.access$300(AbstractOperationContext.java:1185)
        at org.jboss.as.controller.AbstractOperationContext.executeResultHandlerPhase(AbstractOperationContext.java:767)
        at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:644)
        at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
        at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1344)
        at org.jboss.as.controller.ModelControllerImpl.internalExecute(ModelControllerImpl.java:392)
        at org.jboss.as.controller.ModelControllerImpl.execute(ModelControllerImpl.java:217)
        at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler.doExecute(ModelControllerClientOperationHandler.java:208)
        at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler.access$300(ModelControllerClientOperationHandler.java:130)
        at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler$1$1.run(ModelControllerClientOperationHandler.java:152)
        at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler$1$1.run(ModelControllerClientOperationHandler.java:148)
        at java.security.AccessController.doPrivileged(AccessController.java:595)
        at javax.security.auth.Subject.doAs(Subject.java:569)
        at org.jboss.as.controller.AccessAuditContext.doAs(AccessAuditContext.java:92)
        at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler$1.execute(ModelControllerClientOperationHandler.java:148)
        at org.jboss.as.protocol.mgmt.AbstractMessageHandler$ManagementRequestContextImpl$1.doExecute(AbstractMessageHandler.java:363)
        at org.jboss.as.protocol.mgmt.AbstractMessageHandler$AsyncTaskRunner.run(AbstractMessageHandler.java:472)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:785)
        at org.jboss.threads.JBossThread.run(JBossThread.java:320)


```

It seems to hang until that 300 sec. timeout is hit, though the test passes.

That's all I need for now, so I'm unlikely to pursue, but thought I'd mention this issue.

**Comment by radcortez** [comment]
Hi @scottkurz thank you for your comments.

When I first write this, it was for Wildfly 8 and as far as I remember it was working ok. Maybe something changed in Wildfly 10 that is causing the issue.

I'll have a look! Cheers :)

**Comment by radcortez** [comment]
Hi @scottkurz,

I had a look into the issue and it seems this is caused by a different behaviour in the `org.jberet.operations.JobOperatorImpl#getRunningExecutions` between the implementations.

When Wildfly is undeploying an application, it verifies if there are still jobs running to stop them. This is done by calling the `org.jberet.operations.JobOperatorImpl#getRunningExecutions`. In JBeret, it returns an empty list, but in Spring Batch throws a `NoSuchJobException`. The RI has the same behaviour of Spring Batch.

Also had a look into the TCK and it seems there is no specific test for this. Only `com.ibm.jbatch.tck.tests.jslxml.JobOperatorTests#testJobOperatorGetRunningJobInstancesException`, but it only tests for a job that actually doesn't exit, not a job that exists and is not running.

The spec itself is not clear on what the correct behaviour should be. I'll email the EG list and after confirmation I can contribute with a test for the TCK :)
